[
    {"options":"Manufacturing",},
    {"options":"Construction materials"},
    {"options":"Electronics and Optics"},
    {"options":"Food and Beverage"},
    {"options":"Bakery & confectionery products"},
    {"options":"Beverages"},
    {"options":"Fish & fish products"},
    {"options":"Meat & meat products"},
    {"options":"Milk & dairy products"},
    {"options":"Other"},
    {"options":"Sweets & snack food"},
    {"options":"Furniture"},
    {"options":"Bathroom/sauna"},
    {"options":"Bedroom"},
    {"options":"Children's room"},
    {"options":"Kitchen"},
    {"options":"Living room"},
    {"options":"Office"},
    {"options":"Other (Furniture)"},
    {"options":"Outdoor"},
    {"options":"Project furniture"},
    {"options":"Other"},
    {"options":"Metal structures"},
    {"options":"Ship repair and conversion"},
    {"options":"Boat/Yacht building"},
    {"options":"Aluminium and steel workboats"},
    {"options":"Maritime"},
    {"options":"Manufacture of machinery"},
    {"options":"Machinery equipment/tools"},
    {"options":"Machinery components"},
    {"options":"Machinery"},
    {"options":"Repair and maintenance service"},
    {"options":"Metalworking"},
    {"options":"Houses and buildings"},
    {"options":"Metal products"},
    {"options":"Metal works"},
    {"options":"CNC-machining"},
    {"options":"Forgings, Fasteners"},
    {"options":"Gas, Plasma, Laser cuttin"},
    {"options":"MIG, TIG, Aluminum welding"},
    {"options":"Plastic and Rubber"},
    {"options":"Packaging"},
    {"options":"Plastic goods"},
    {"options":"Plastic processing technology"},
    {"options":"Blowing"},
    {"options":"Moulding"},
    {"options":"Plastics welding and processing"},
    {"options":"Plastic profiles"},
    {"options":"Printing"},
    {"options":"Advertising"},
    {"options":"Book/Periodicals printing"},
    {"options":"Labelling and packaging printing"},
    {"options":"Clothing"},
    {"options":"Textile"},
    {"options":"Wood"},
    {"options":"Other (Wood)"},
    {"options":"Wooden building materials"},
    {"options":"Wooden houses"},
    {"options":"Other"},
    {"options":"Creative industries"},
    {"options":"Energy technology"},
    {"options":"Environment"},
    {"options":"Service"},
    {"options":"Business services"},
    {"options":"Engineering"},
    {"options":"Information Technology and Telecommunications"},
    {"options":"Data processing, Web portals, E-marketing"},
    {"options":"Programming, Consultancy"},
    {"options":"Software, Hardware"},
    {"options":"Telecommunications"},
    {"options":"Tourism"},
    {"options":"Translation services"},
    {"options":"Transport and Logistics"},
    {"options":"Air"},
    {"options":"Rail"},
    {"options":"Road"},
    {"options":"Water"},
    ]



    // ["Manufacturing", 
    // "Construction materials",
    // "Electronics and Optics",
    // "Food and Beverage",
    // "Bakery & confectionery products",
    // "Beverages",
    // "Fish & fish products",
    // "Meat & meat products",
    // "Milk & dairy products",
    // "Other",
    // "Sweets & snack food",
    // "Furniture",
    // "Bathroom/sauna",
    // "Bedroom",
    // "Children’s room",
    // "Kitchen",
    // "Living room",
    // "Office",
    // "Other (Furniture)",
    // "Outdoor",
    // "Project furniture",
    // "Other",
    // "Metal structures",
    // "Ship repair and conversion",
    // "Boat/Yacht building",
    // "Aluminium and steel workboats",
    // "Maritime",
    // "Manufacture of machinery",
    // "Machinery equipment/tools",
    // "Machinery components",
    // "Machinery",
    // "Repair and maintenance service",
    // "Metalworking",
    // "Houses and buildings",
    // "Metal products",
    // "Metal works",
    // "CNC-machining",
    // "Forgings, Fasteners",
    // "Gas, Plasma, Laser cutting",
    // "MIG, TIG, Aluminum welding",
    // "Plastic and Rubber",
    // "Packaging",
    // "Plastic goods",
    // "Plastic processing technology",
    // "Blowing",
    // "Moulding",
    // "Plastics welding and processing",
    // "Plastic profiles",
    // "Printing",
    // "Advertising",
    // "Book/Periodicals printing",
    // "Labelling and packaging printing",
    // "Clothing",
    // "Textile",
    // "Wood",
    // "Other (Wood)",
    // "Wooden building materials",
    // "Wooden houses",
    // "Other",
    // "Creative industries",
    // "Energy technology",
    // "Environment",
    // "Service",
    // "Business services",
    // "Engineering",
    // "Information Technology and Telecommunications",
    // "Data processing, Web portals, E-marketing",
    // "Programming, Consultancy",
    // "Software, Hardware",
    // "Telecommunications",
    // "Tourism",
    // "Translation services",
    // "Transport and Logistics",
    // "Air",
    // "Rail",
    // "Road",
    // "Water",
    // ]